version: "3.7"

services:
    djangoapp:
        build:
            context: ./covapp
        image: coronaapp:vivek
        environment:
            DJANGO_MANAGEPY_MIGRATE: "on"
        ports:
            - 8000:8000
        env_file:
            - ./.env